"use client";

import {
  ShieldCheck,
  Brain,
  AlertTriangle,
  TrendingUp,
} from "lucide-react";

export default function RiskAnalytics() {
  const trustScore = 97;
  const confidence = 98;
  const scamProbability = 3;

  return (
    <div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">

      <div className="mb-8">

        <h2 className="text-2xl font-bold text-slate-900">
          AI Risk Analytics
        </h2>

        <p className="mt-2 text-slate-500">
          Real-time recruitment intelligence generated by CareerGuardian AI.
        </p>

      </div>

      {/* Main Score */}

      <div className="rounded-3xl bg-gradient-to-r from-blue-600 to-violet-600 p-8 text-center text-white">

        <ShieldCheck className="mx-auto h-12 w-12" />

        <h1 className="mt-4 text-6xl font-extrabold">
          {trustScore}%
        </h1>

        <p className="mt-2 text-lg">
          Recruitment Trust Score
        </p>

      </div>

      {/* Analytics */}

      <div className="mt-8 space-y-5">

        <AnalyticsRow
          icon={<Brain className="h-5 w-5 text-blue-600" />}
          title="AI Confidence"
          value={`${confidence}%`}
          color="bg-blue-500"
        />

        <AnalyticsRow
          icon={<AlertTriangle className="h-5 w-5 text-red-600" />}
          title="Scam Probability"
          value={`${scamProbability}%`}
          color="bg-red-500"
        />

        <AnalyticsRow
          icon={<TrendingUp className="h-5 w-5 text-green-600" />}
          title="Risk Level"
          value="LOW"
          color="bg-green-500"
        />

      </div>

    </div>
  );
}

function AnalyticsRow({
  icon,
  title,
  value,
  color,
}: {
  icon: React.ReactNode;
  title: string;
  value: string;
  color: string;
}) {
  return (
    <div className="rounded-2xl border p-5">

      <div className="mb-2 flex items-center justify-between">

        <div className="flex items-center gap-3">

          {icon}

          <span className="font-semibold">
            {title}
          </span>

        </div>

        <span className="font-bold">
          {value}
        </span>

      </div>

      <div className="h-2 overflow-hidden rounded-full bg-slate-200">

        <div
          className={`h-full rounded-full ${color}`}
          style={{
            width: value.includes("%")
              ? value
              : "100%",
          }}
        />

      </div>

    </div>
  );
}