import jsPDF from "jspdf";

export default function downloadInterviewReport(
  result: any
) {

  const pdf = new jsPDF("p", "mm", "a4");

  const pageWidth = pdf.internal.pageSize.getWidth();

  const center = pageWidth / 2;

  // Background

  pdf.setFillColor(245, 248, 255);

  pdf.rect(0, 0, pageWidth, 297, "F");

  // Header

  pdf.setFillColor(25, 118, 210);

  pdf.rect(0, 0, pageWidth, 30, "F");

  pdf.setFont("helvetica", "bold");

  pdf.setTextColor(255, 255, 255);

  pdf.setFontSize(22);

  pdf.text(
    "GUARDIAN AI",
    center,
    12,
    {
      align: "center",
    }
  );

  pdf.setFontSize(13);

  pdf.text(
    "Professional Interview Assessment Report",
    center,
    21,
    {
      align: "center",
    }
  );

  pdf.setTextColor(40, 40, 40);

  pdf.setFontSize(11);

  pdf.text(
    `Generated : ${new Date().toLocaleString()}`,
    15,
    42
  );

  // Overall Score

  pdf.setDrawColor(210);

  pdf.roundedRect(
    15,
    50,
    180,
    35,
    4,
    4
  );

  pdf.setFontSize(18);

  pdf.setFont(
    "helvetica",
    "bold"
  );

  pdf.text(
    "Overall Interview Score",
    center,
    62,
    {
      align: "center",
    }
  );

  pdf.setTextColor(0, 102, 204);

  pdf.setFontSize(32);

  pdf.text(
    `${result.overall}%`,
    center,
    78,
    {
      align: "center",
    }
  );

  pdf.setTextColor(30, 30, 30);

  // Section Heading

  pdf.setFontSize(16);

  pdf.setFont(
    "helvetica",
    "bold"
  );

  pdf.text(
    "Interview Performance",
    15,
    100
  );

  pdf.setFontSize(12);
    // Performance Scores

  const scores = [

    {
      title: "Technical",
      value: result.technical,
      color: [33, 150, 243],
    },

    {
      title: "Communication",
      value: result.communication,
      color: [76, 175, 80],
    },

    {
      title: "Confidence",
      value: result.confidence,
      color: [255, 152, 0],
    },

    {
      title: "Problem Solving",
      value: result.problemSolving,
      color: [156, 39, 176],
    },

  ];

  let y = 112;

  scores.forEach((item) => {

    pdf.setFont("helvetica", "bold");

    pdf.setFontSize(12);

    pdf.setTextColor(40);

    pdf.text(item.title, 18, y);

    // Background Bar

    pdf.setFillColor(225, 225, 225);

    pdf.roundedRect(
      65,
      y - 4,
      100,
      6,
      3,
      3,
      "F"
    );

    // Filled Bar

    pdf.setFillColor(
      item.color[0],
      item.color[1],
      item.color[2]
    );

    pdf.roundedRect(
      65,
      y - 4,
      item.value,
      6,
      3,
      3,
      "F"
    );

    pdf.setFontSize(11);

    pdf.text(
      `${item.value}%`,
      172,
      y
    );

    y += 14;

  });

  // Hiring Probability

  pdf.setDrawColor(210);

  pdf.roundedRect(
    15,
    172,
    180,
    24,
    4,
    4
  );

  pdf.setFontSize(15);

  pdf.setFont(
    "helvetica",
    "bold"
  );

  pdf.text(
    "Hiring Probability",
    20,
    184
  );

  pdf.setTextColor(0, 120, 40);

  pdf.setFontSize(24);

  pdf.text(
    `${result.hiringProbability}%`,
    160,
    186
  );

  pdf.setTextColor(30);

  // Recommendation

  pdf.setFontSize(16);

  pdf.setFont(
    "helvetica",
    "bold"
  );

  pdf.text(
    "Guardian AI Recommendation",
    15,
    212
  );

  pdf.setFont(
    "helvetica",
    "normal"
  );

  pdf.setFontSize(11);

  const recommendation =
    pdf.splitTextToSize(
      result.recommendation,
      175
    );

  pdf.text(
    recommendation,
    15,
    222
  );

  y = 240;
    // Strengths

  pdf.setFont("helvetica", "bold");

  pdf.setFontSize(15);

  pdf.text("Key Strengths", 15, y);

  y += 10;

  pdf.setFont("helvetica", "normal");

  pdf.setFontSize(11);

  (result.strengths || []).forEach((item: string) => {

    pdf.text(`• ${item}`, 20, y);

    y += 7;

  });

  y += 5;

  // Improvements

  pdf.setFont("helvetica", "bold");

  pdf.setFontSize(15);

  pdf.text("Areas for Improvement", 15, y);

  y += 10;

  pdf.setFont("helvetica", "normal");

  pdf.setFontSize(11);

  (result.improvements || []).forEach((item: string) => {

    pdf.text(`• ${item}`, 20, y);

    y += 7;

  });

  y += 10;

  // Footer

  pdf.setDrawColor(220);

  pdf.line(15, 280, 195, 280);

  pdf.setFont("helvetica", "italic");

  pdf.setFontSize(10);

  pdf.setTextColor(120);

  pdf.text(
    "Generated by Guardian AI Interview Simulator",
    pageWidth / 2,
    286,
    {
      align: "center",
    }
  );

  pdf.save("Guardian_Interview_Report.pdf");

}