"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BriefcaseBusiness, ExternalLink, MapPin } from "lucide-react";

interface Job { _id: string; company: string; jobTitle: string; location: string; employmentType: string; skills: string[]; matchScore: number; matchedReasons: string[]; postedAt: string; jobUrl: string; }

export default function JobsPage() {
  const [jobs, setJobs] = useState<Job[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/jobs/recommendations", { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error("Unable to load opportunities"); const result = await response.json(); setJobs(result.jobs || []); }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  return <main className="min-h-screen bg-slate-100"><section className="mx-auto max-w-6xl px-6 py-10"><Link href="/dashboard" className="inline-flex items-center gap-2 font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft className="h-4 w-4" />Back to Dashboard</Link><div className="mt-8 flex items-end justify-between gap-4"><div><p className="font-bold uppercase tracking-[0.2em] text-cyan-600">CareerGuardian AI</p><h1 className="mt-2 text-4xl font-black text-slate-900">Recommended Opportunities</h1><p className="mt-2 text-slate-500">Openings ranked against your Career DNA and preferences.</p></div><BriefcaseBusiness className="hidden h-14 w-14 text-cyan-600 md:block" /></div>{loading && <p className="mt-12 text-slate-500">Finding your best matches...</p>}{error && <p className="mt-12 rounded-2xl bg-red-50 p-5 text-red-700">{error}</p>}{!loading && !error && jobs.length === 0 && <div className="mt-10 rounded-3xl bg-white p-10 text-center shadow-sm"><h2 className="text-2xl font-bold text-slate-900">No matches yet</h2><p className="mt-2 text-slate-500">Complete your Career DNA and enable job notifications to see relevant openings.</p></div>}<div className="mt-10 grid gap-6 md:grid-cols-2">{jobs.map((job) => <article key={job._id} className="rounded-3xl bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="flex items-start justify-between gap-4"><div><p className="font-bold text-cyan-700">{job.company}</p><h2 className="mt-1 text-2xl font-black text-slate-900">{job.jobTitle}</h2></div><div className="rounded-2xl bg-emerald-50 px-3 py-2 text-center text-emerald-700"><strong className="block text-xl">{job.matchScore}%</strong><span className="text-xs font-bold">MATCH</span></div></div><div className="mt-5 flex flex-wrap gap-3 text-sm font-semibold text-slate-600"><span className="inline-flex items-center gap-1"><MapPin className="h-4 w-4" />{job.location}</span><span>{job.employmentType}</span></div><div className="mt-5 flex flex-wrap gap-2">{job.skills.map((skill) => <span key={skill} className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{skill}</span>)}</div><ul className="mt-5 space-y-1 text-sm text-slate-600">{job.matchedReasons.map((reason) => <li key={reason}>✓ {reason}</li>)}</ul><p className="mt-5 text-xs text-slate-400">Posted {new Date(job.postedAt).toLocaleDateString()}</p><button type="button" onClick={() => window.open(job.jobUrl, "_blank", "noopener,noreferrer")} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 px-5 py-3 font-bold text-white"><ExternalLink className="h-4 w-4" />View Job Opening</button></article>)}</div></section></main>;
}
